(in-package :wolfs-den-lisp)

(defparameter *swatch* (make-hash-table :test 'equal))
(defmacro define-color (color-name color-value)
  `(setf (gethash ,color-name *swatch*) ,color-value))

(defparameter *sepia* (blt:rgba 191 171 143))
(defparameter *dark-sepia* (blt:rgba 120 101 97))

(define-color "yellow" (blt:yellow))
(define-color "blue" (blt:blue))
(define-color "sepia" *sepia*)
(define-color "transparent" (blt:rgba 0 0 0 0))
(define-color "white" (blt:white))
(define-color "stairs" (blt:yellow))
(define-color "stone" (blt:rgba 120 120 120))
(define-color "dark-stone" (blt:rgba 120 120 120 128))
(define-color "wood" (blt:rgba 191 171 143))
(define-color "undead" (blt:rgba 220 115 255))
(define-color "timberwolf" *sepia*)
(define-color "red" (blt:red))
(define-color "oak" (blt:rgba 191 171 143 192))
(define-color "iron" (blt:rgba 150 150 150))
(define-color "steel" (blt:rgba 183 180 177))
(define-color "bone" (blt:rgba 223 223 223))
(define-color "blackiron" (blt:rgba 95 0 191))

(defun color-from-name (color-string)
  (or (gethash color-string *swatch*) 
      (error (format nil "No color ~a in swatch" color-string))))
